/**
 * Fleet v2 HTTP API
 * HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: jiri.strouhal@bringauto.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Payload_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Payload_data::Payload_data()
{
m_Json = web::json::value::object();
    m_JsonIsSet = false;
}

Payload_data::~Payload_data()
{
}

void Payload_data::validate()
{
    // TODO: implement validation
}

web::json::value Payload_data::toJson() const
{
return m_Json;
}

bool Payload_data::fromJson(const web::json::value& val)
{
    bool ok = true;

    web::json::value refVal_setJson;
    ok &= ModelBase::fromJson(val, refVal_setJson);
    setJson(refVal_setJson);
    
    return ok;
}

void Payload_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
}

bool Payload_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    return ok;
}

web::json::value Payload_data::getJson() const
{
    return m_Json;
}

void Payload_data::setJson(const web::json::value& value)
{
    m_Json = value;
    m_JsonIsSet = true;
}

bool Payload_data::jsonIsSet() const
{
    return m_JsonIsSet;
}

void Payload_data::unsetJson()
{
    m_JsonIsSet = false;

}

}
}
}
}
