/**
 * Fleet v2 HTTP API
 * HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: jiri.strouhal@bringauto.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CarApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Car.h"
#include <vector>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  CarApi 
{
public:

    explicit CarApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CarApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Return list of available cars for all companies registered in the database.
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<Car>>> availableCars(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_ */

