/**
 * Fleet v2 HTTP API
 * HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.
 *
 * The version of the OpenAPI document: 2.4.0
 * Contact: jiri.strouhal@bringauto.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CarApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_



#include "bringauto-fleet-http-client-generated/ApiClient.h"

#include "bringauto-fleet-http-client-generated/model/Car.h"
#include <vector>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  CarApi 
{
public:

    explicit CarApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CarApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Return list of available cars for all companies registered in the database.
    /// </remarks>
    /// <param name="wait">An empty parameter. If specified, the method waits for predefined period of time, until some data to be sent in response are available. (optional, default to false)</param>
    /// <param name="since">A Unix timestamp; if specified, the method returns all messages inclusivelly newer than the specified timestamp \\ (i.e., messages with timestamp greater than or equal to the &#39;since&#39; timestamp) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<Car>>> availableCars(
        boost::optional<bool> wait,
        boost::optional<int64_t> since
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_CarApi_H_ */

