/**
 * Fleet v2 HTTP API
 * HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: jiri.strouhal@bringauto.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ModuleApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ModuleApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ModuleApi_H_



#include "bringauto-fleet-http-client-generated/ApiClient.h"

#include "bringauto-fleet-http-client-generated/model/AvailableDevices.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ModuleApi 
{
public:

    explicit ModuleApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ModuleApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Return device Ids for all devices available for contained in the specified car.&lt;br&gt; For a single car module, the device Ids are returned as an object containing module Id and the list of device Ids. &lt;br&gt; If a module Id is specified, only a single such object is returned. &lt;br&gt; Otherwise, a list of such objects is returned, one for each module contained in the car. &lt;br&gt;
    /// </remarks>
    /// <param name="companyName">Name of the company, following a pattern ^[0-9a-z_]+$.</param>
    /// <param name="carName">Name of the Car, following a pattern ^[0-9a-z_]+$.</param>
    /// <param name="moduleId">An Id of module, an unsigned integer. (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AvailableDevices>> availableDevices(
        utility::string_t companyName,
        utility::string_t carName,
        boost::optional<int32_t> moduleId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ModuleApi_H_ */

