/**
 * Fleet v2 HTTP API
 * HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: jiri.strouhal@bringauto.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Car.h
 *
 * A car assigned to a particular company.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Car_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Car_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// A car assigned to a particular company.
/// </summary>
class  Car
    : public ModelBase
{
public:
    Car();
    virtual ~Car();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Car members

    /// <summary>
    /// Name of the company, following a pattern ^[0-9a-z_]+$
    /// </summary>
    utility::string_t getCompanyName() const;
    bool companyNameIsSet() const;
    void unsetCompany_name();

    void setCompanyName(const utility::string_t& value);

    /// <summary>
    /// Name of the Car, following a pattern ^[0-9a-z_]+$
    /// </summary>
    utility::string_t getCarName() const;
    bool carNameIsSet() const;
    void unsetCar_name();

    void setCarName(const utility::string_t& value);


protected:
    utility::string_t m_Company_name;
    bool m_Company_nameIsSet;
    utility::string_t m_Car_name;
    bool m_Car_nameIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Car_H_ */
