#pragma once

constexpr int MAX_REQUEST_THRESHOLD_COUNT {5};
constexpr int MAX_REQUEST_THRESHOLD_PERIOD_MS {10};
constexpr int DELAY_AFTER_THRESHOLD_REACHED_MS {5000};
constexpr int RETRY_REQUESTS_DELAY_MS {200};

constexpr int MAX_ALLOWED_NO_DELAY_TIME_DIFFERENCE_MS {50};
constexpr int MAX_ALLOWED_TIME_DIFFERENCE_PERCENTAGE {5};
constexpr int MAX_DELAY_AFTER_THRESHOLD_REACHED_MS {
    DELAY_AFTER_THRESHOLD_REACHED_MS + (DELAY_AFTER_THRESHOLD_REACHED_MS * MAX_ALLOWED_TIME_DIFFERENCE_PERCENTAGE / 100)
};
constexpr int MAX_RETRY_REQUESTS_DELAY_MS {
    RETRY_REQUESTS_DELAY_MS + (RETRY_REQUESTS_DELAY_MS * MAX_ALLOWED_TIME_DIFFERENCE_PERCENTAGE / 100)
};